### PR TITLE
Feature osm profile pedestrian

### PR DESCRIPTION
**Pull request by skinkie**
I'll be evaluating these changes shortly. Suggestions welcome.

### CODE REVIEW

**Comment by ben-strasser** [comment]
Hi,

thanks for the patches. I had a quick look. I'll merge some parts next week when I find the time for in-depth look.

A few comments:
* I do not want to rename SimpleOSMCarRoutingGraph to SimpleOSMRoutingGraph. I prefer having a SimpleOSMPredestrianRoutingGraph. The rational is that not all properties that make sense for pedestrians and cars alike. For example for pedestrians a distinction between geo_distance and travel_time is probably not necessary as one probably always assumes a constant walking speed. Another example are the currently not extracted turn restrictions. These are only needed by Cars.

* The proposed is_osm_way_used_by_pedestrians results false if access=agricultural or access=forestry. I think that at least if you want to go jogging in rural areas, then you want to walk along these ways. There are probably other such tags.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
Thanks for your feedback. I'll make it so. I also thought about the case where the walking speed wouldn't be equal to the _static value_.

**Comment by ben-strasser** [comment]
Hi,

Another access value that is used is "public" 
https://taginfo.openstreetmap.org/keys/access#values
I do not know what the intend of this value is but it sounds like something where you are allowed to walk.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
The problem with the current negation approach is that everything must be allowed, otherwise it breaks. For example _public_ I can't find it back here: https://wiki.openstreetmap.org/wiki/Key:access

In my own planner I implemented the access restrictions as two-level negations, like you have implemented it as motor_vehicle, if the setting is no, then remove it, when explictly yes, it can override another setting. The whole thing is very subtile, which is currently not really covered in your model. As example, a highway=cycleway with motorcar=yes would be filtered in your code, while in mine this would grant the car. The difference between explicit restrictions, and _too early_ inferred restrictions.

**Comment by ben-strasser** [comment]
Hi,

> For example /public/ I can't find it back here: https://wiki.openstreetmap.org/wiki/Key:access

There are quite a few tags not documented on the wiki unfortunately. Sometimes the wiki documentations also do not mirror how people actually use some tags. My approach is to either look at usage examples and infer the intended meaning or look at what other routing engines do.

To find usage examples, one can add an if to the RoutingKit parser and call the logging callback with the IDs of corresponding entities. 

(I'm not saying that correctly supporting access=public is super important, it's just one of those things that are semi-easy to do, when one is touching that part of the code anyway.)

On 12/03/2016 10:47 PM, Stefan de Konink wrote:
> The problem with the current negation approach is that everything must be allowed, otherwise it breaks. For example /public/ I can't find it back here: https://wiki.openstreetmap.org/wiki/Key:access
> 
> In my own planner I implemented the access restrictions as two-level negations, like you have implemented it as motor_vehicle, if the setting is no, then remove it, when explictly yes, it can override another setting. The whole thing is very subtile, which is currently not really covered in your model. As example, a highway=cycleway with motorcar=yes would be filtered in your code, while in mine this would grant the car. The difference between explicit restrictions, and /too early/ inferred restrictions.

If I understand you correctly, then it is a question of in what order to test the various conditions, i.e., in what order to arrange the if-statements. The current code is definitely not perfect in this regard. It was written to get some initial code that works most of the time. I'm open to restructuring the order in which the conditions are evaluated. The only restriction is that the evaluation must remain fast.

Best Regards
Ben Strasser

**Comment by ben-strasser** [comment]
Hi,

Thanks for the patch. I added a slight variation of your code. 

The code that I added has access=public as open. An example usage is https://www.openstreetmap.org/way/22720834 . Further I removed travel_time from the returned graph. As long as travel_time = some_constant*geo_distance one can also directly use the later.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
@ben-strasser how do you handle the case where the user is faster or slower at a certain location? For example steps, ferries, etc.?

**Comment by ben-strasser** [comment]
Hi,

> p.s. you didn't push yet ;)

I'm confused. Is this not the push?: https://github.com/RoutingKit/RoutingKit/commit/2e17e4658b2bee706be11073d3ac00f96661011e


There are two reasons why I do not want to have a travel_time

1. I do not think that you can say that a generic pedestrian is faster at some place than another. For an elderly person you can definitely but to support special categories of people you need to dig into the OSM extraction details anyway. The simplified interface is not for those users. Most ferries work based on a timetable. There is no mapping onto a scalar edge weight that is not broken anyway.

2. There currently is no implementation for which travel_time is not constant*geo_distance. The only reason to have travel_time would be to future proof, i.e., code would magically pickup the behavior when someone implements some logic. Does one want this to happen automatically? I do not think so, as I expect this to introduce bugs in user code. Not having travel_time prevents users from using it. Further, it does not hamper one from adding one in the future. Finally, user code written now will use geo_distance and thus behave exactly the same if travel_time would get added. The potential change would thus be backward compatible.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
> I'm confused. Is this not the push?: 2e17e46

Github was slow I guess.

> I do not think that you can say that a generic pedestrian is faster at some place than another.

I see some use-cases that reduce or increase speed due to climbing and descending, I would call it _resistance_. This would help to model escalators as well.

And further agree with you that KISS is better than a gazillion half implemented interfaces :)

**Pull request closed without merging**
