### PR TITLE
Feature osm profile bicycle

### PR DESCRIPTION
**Pull request by skinkie**
First attempt to create a simple bicycle profile.

@ben-strasser I am interested in making some sort of weighted implementation analogue to the way_speed for the car profile. Hence prefer highway=cycleway over highway=* and do something with the length of the sections plus trafficlights on the last node of the edge. Good idea?

### CODE REVIEW

**Comment by skinkie** [comment]
This full request missed the most pretty thing!

Image route using bicycle-profile

**Comment by skinkie** [comment]
Keep this one on hold a bit. Some of the advanced interpretation stuff, especially to get the way open in both directions should get in.

**Comment by ben-strasser** [comment]
Hi,

thanks for the patch.

> Keep this one on hold a bit.

Are you still working or it or is it "finished"?

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
"finished"

But after the merge I'll consider building a traveltime profile as well.

**Comment by ben-strasser** [comment]
Hi,

you have two implementations of get_osm_bicycle_direction_category. They do not do the same thing. There are some very subtle differences:

```cpp
		*cycleway_left = tags["cycleway_left"],
		*cycleway_right = tags["cycleway_right"],
```

vs

```cpp
+		*cycleway_left  = tags["cycleway:left"],
+		*cycleway_right = tags["cycleway:right"],
```

According to https://taginfo.openstreetmap.org/keys "cycleway:left" exists but there is no "cycleway_left". You current patch uses the underscore version. Is this a bug?

Why not use the more "complex" get_osm_bicycle_direction_category in the code?

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
> According to https://taginfo.openstreetmap.org/keys "cycleway:left" exists but there is no "cycleway_left". You current patch uses the underscore version. Is this a bug?

That would be a bug indeed.

> Why not use the more "complex" get_osm_bicycle_direction_category in the code?

What do you mean? This code is used right?

https://github.com/RoutingKit/RoutingKit/pull/26/commits/29bc704ed0b95e6ad7bc6a1754b74f5279b091f2#diff-cbcd461bcf304f3be6c1c08f3e58797aR115

**Comment by ben-strasser** [comment]
Hi,

My coments are based upon

https://github.com/RoutingKit/RoutingKit/pull/26/files

There are two versions of get_osm_bicycle_direction_category. The one is "documentation" and in doc/OpenStreetMap_Bicycle_Direction.md. The other one is actually being used. From the "documentation" I gathered, that the version in the "documentation" is complex and therefore not used.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
Regarding the complex version. I have implemented it to get an idea of all the edge cases possible. But it would just boil down to something more simple for routing. My reasoning was that if anyone would start to look for an implementation to render arcs based on what information in tagged in OpenStreetMap this could be a good startingpoint to differentiate between the different road types as 'classes'.

**Comment by ben-strasser** [comment]
> But it would just boil down to something more simple for routing. 

As far as I can tell, the two code versions that you wrote do different things.

For example, the "complex" version says that if cycleway=both then the way is open in both directions regardless of other tags such as the oneway tag. However, the "simple" version gets to a different result if cycleway=both is combined with for example oneway=1. I do not know whether oneway only applies to cars and bicycles can drive both ways so I do not know which version is correct. However, they do different things.

**Comment by skinkie** [comment]
> For example, the "complex" version says that if cycleway=both then the way is open in both directions regardless of other tags such as the oneway tag.

You meant cycleway:both :) In my understanding all OpenStreetMap ways are bidirectional. Cycleway is not bidirectional. So a directional way can be come bidirectional for bicycles:
- cycleway:both 
- cycleway:right=opposite cycleway:left=opposite
- oneway:bicycle=no

**Comment by ben-strasser** [comment]
Hi,

I had a look at the OSM-Wiki page. Am I missing something or would
```cpp
OSMWayDirectionCategory get_osm_bicycle_direction_category(uint64_t osm_way_id, const TagMap&tags, std::function<void(const std::string&)>log_message){
	const char*junction = tags["junction"];
	if(junction != nullptr && str_eq(junction, "roundabout"))
		return OSMWayDirectionCategory::only_open_forwards;

	const char*tag_name = "oneway:bicycle";

	const char*oneway = tags[tag_name];
	if(oneway == nullptr){
		tag_name = "oneway";
		oneway = tags[tag_name];
	}
	
	if(oneway == nullptr)
		return OSMWayDirectionCategory::open_in_both;

	if(str_eq(oneway, "-1") || str_eq(oneway, "reverse") || str_eq(oneway, "backward")) {
		return OSMWayDirectionCategory::only_open_backwards;
	} else if(str_eq(oneway, "yes") || str_eq(oneway, "true") || str_eq(oneway, "1")) {
		return OSMWayDirectionCategory::only_open_forwards;
	} else if(str_eq(oneway, "no") || str_eq(oneway, "false") || str_eq(oneway, "0")) {
		return OSMWayDirectionCategory::open_in_both;
	} else if(str_eq(oneway, "reversible") || str_eq(oneway, "alternating")) {
		return OSMWayDirectionCategory::closed;
	} else {
		log_message("Warning: OSM way "+std::to_string(osm_way_id)+" has unknown oneway tag value \""+oneway+"\" for \""+tag_name+"\". Way is closed.");
	}
}
```
get the job done? 

The Wiki page sound overly complicated. I fear that many people tagging OSM will get those tags messed up. The code therefore needs to be robust against "wrong" but reasonable tags.

I found no comment in the wiki about countries where people drive on the left. This is problematic because this means that we cannot use `cycleway:right=lane` to infer that there is a lane in the direction of the way.

I think one additionally wants to add a `BitVector is_dedicated_bicycle_way` to `SimpleOSMBicycleRoutingGraph` to allow the routing engine to slightly prefer ways going over `highway=cycleway` ways and maybe roads with bicycle lanes with `segregated=yes`.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
I don't think this works out, because the "Way A : highway=*[1] + oneway=yes + cycleway=opposite" isn't covered. Regarding to left/right, in my perspective this is related to the direction of the way, in the data.

Your suggestion regarding the BitVector sounds awesome, also for pedestrians, but more importantly for my other use case: public transport buses. Could you give a small example how the preference could be implemented using this BitVector?

**Comment by ben-strasser** [comment]
Indeed, that case is not handled correctly. How about:

```cpp
OSMWayDirectionCategory get_osm_bicycle_direction_category(uint64_t osm_way_id, const TagMap&tags, std::function<void(const std::string&)>log_message){
	const char*oneway_bicycle = tags["oneway:bicycle"];
	if(oneway_bicycle != nullptr){
		if(str_eq(oneway_bicycle, "-1") || str_eq(oneway_bicycle, "opposite"))
			return OSMWayDirectionCategory::only_open_backwards;

		if(str_eq(oneway_bicycle, "1") || str_eq(oneway_bicycle, "yes"))
			return OSMWayDirectionCategory::only_open_forwards;
	
		if(str_eq(oneway_bicycle, "tolerated") || str_eq(oneway_bicycle, "permissive"))
			return OSMWayDirectionCategory::open_in_both;
			
		log_message("Warning: OSM way "+std::to_string(osm_way_id)+" has unknown oneway tag value \""+oneway_bicycle+"\" for \"oneway:bicycle\". Way is closed.");
		return OSMWayDirectionCategory::closed;
	}

	const char*cycleway = tags["cycleway"];
	if(cycleway != nullptr){
		if(str_eq(cycleway, "opposite") || str_eq(cycleway, "opposite_track") || str_eq(cycleway, "opposite_lane") || str_eq(cycleway, "opposite_share_busway")){
			const char*oneway = tags["oneway"];
			if(oneway != nullptr && (str_eq(oneway, "-1") || str_eq(oneway, "reverse") || str_eq(oneway, "backward")))
				return OSMWayDirectionCategory::only_open_backwards;
			else
				return OSMWayDirectionCategory::open_in_both;

		}
	}

	return get_osm_car_direction_category(osm_way_id, tags, log_message);
}
```
I included various tags in the code that are used according to https://taginfo.openstreetmap.org but are not documented in the Wiki.

> Your suggestion regarding the BitVector sounds awesome, also for pedestrians, but more importantly for my other use case: public transport buses. Could you give a small example how the preference could be implemented using this BitVector?

Very similar to how `get_osm_way_speed` is implemented. You can look at this as a "speed" value with one bit of information.

**Comment by skinkie** [comment]
In your last example you don't handle the cycleway:left/cycleway:right or cycleway:both combination which also grant open_in_both.

**Comment by ben-strasser** [comment]
Hi,

Why does cycleway:right combined with oneway=1 in continental Europe grant open_in_both direction?

The issue with cycleway:both is correct though.

Best Regards
Ben

**Comment by skinkie** [comment]
cycleway:right + cycleway:left ~ cycleway:both ~ oneway:bicycle = no
(cycleway:left = opposite || cycleway:right = opposite) ~ oneway:bicycle = no

**Comment by ben-strasser** [comment]
Hi,

I do not understand what you want to tell me.

In what direction should the a way with "cycleway:right=lane" and "oneway=yes" be open for bicycles? From my understanding the cars are allowed to drive forward but not backward. Further, bicycles have their own lane on the right side of the road. In continental Europe one drives on the right and therefore the bicycle lane also goes forward. Bicycles can thus drive forward using either the normal road pretending that they are cars or go forward and use their dedicated lane. They cannot go backwards. "cycleway:right=lane" thus does not imply open_in_both.

The problem with "cycleway:right=lane" is that in England, where people drive on the left, the exact same tag combination (i.e. "cycleway:right=lane" and "oneway=yes") has a different meaning and implies that the way is open in both direction for bicycles. This difference between England and continental Europe is the reason why I try to make the logic in the code not depend on "cycleway:right" or "cycleway:left".

Best Regards 
Ben Strasser

**Comment by skinkie** [comment]
If (cycleway:right=* and cycleway:left=*) || (cycleway:both=*) || (oneway:bicycle=no) then open_in_both.

Because roads that have bicycle tracks on both sides will have bidirectional bicycleways.

if (cycleway:left = opposite || cycleway:right = opposite) || (oneway:bicycle=no) then open_in_both;

Because a road (if provided with oneway=*) would become directional, a cyclist would be still allowed to go on that directional road in the oneway direction, but is now also allowed to go in the opposite direction by either cycleway:left or cycleway:right.

**Comment by ben-strasser** [comment]
What should happen with "oneway_bicycle=no_planned"? For example: https://www.openstreetmap.org/way/5134711

Do you see any problems with the following code?
```cpp
OSMWayDirectionCategory get_osm_bicycle_direction_category(uint64_t osm_way_id, const TagMap&tags, std::function<void(const std::string&)>log_message){
	const char*oneway_bicycle = tags["oneway:bicycle"];
	if(oneway_bicycle != nullptr){
		if(str_eq(oneway_bicycle, "-1") || str_eq(oneway_bicycle, "opposite"))
			return OSMWayDirectionCategory::only_open_backwards;

		if(str_eq(oneway_bicycle, "1") || str_eq(oneway_bicycle, "yes") || str_eq(oneway_bicycle, "true") || str_eq(oneway_bicycle, "no_planned"))
			return OSMWayDirectionCategory::only_open_forwards;
	
		if(str_eq(oneway_bicycle, "0") || str_eq(oneway_bicycle, "no") || str_eq(oneway_bicycle, "false") || str_eq(oneway_bicycle, "tolerated") || str_eq(oneway_bicycle, "permissive"))
			return OSMWayDirectionCategory::open_in_both;
			
		log_message("Warning: OSM way "+std::to_string(osm_way_id)+" has unknown oneway tag value \""+oneway_bicycle+"\" for \"oneway:bicycle\". Way is closed.");
		return OSMWayDirectionCategory::closed;
	}

	const char*oneway = tags["oneway"];
	if(oneway == nullptr){
		return OSMWayDirectionCategory::open_in_both;
	}else{
		if(str_eq(oneway, "no") || str_eq(oneway, "false") || str_eq(oneway, "0")) {
			return OSMWayDirectionCategory::open_in_both;
		}

		const char*cycleway = tags["cycleway"];
		if(cycleway != nullptr){
			// "opposite" is interpreted as the other direction than cars are allowed. 
			// This is not necessarily opposite to the direction of the OSM way.
			// 
			// A consequence is that "cycleway=opposite" combined "oneway=-1" does not imply that bicycles are only allowed to drive backwards
			//
			// (Yes, people actually do combine those two tags https://www.openstreetmap.org/way/88925376 )
			if(str_eq(cycleway, "opposite") || str_eq(cycleway, "opposite_track") || str_eq(cycleway, "opposite_lane") || str_eq(cycleway, "opposite_share_busway")){
				return OSMWayDirectionCategory::open_in_both;
			}
		}

		const char*cycleway_both = tags["cycleway:both"];
		if(cycleway_both != nullptr)
			return OSMWayDirectionCategory::open_in_both;

		const char*cycleway_left = tags["cycleway:left"];
		const char*cycleway_right = tags["cycleway:right"];
		if(cycleway_left != nullptr && cycleway_right != nullptr)
			return OSMWayDirectionCategory::open_in_both;


		if(str_eq(oneway, "-1") || str_eq(oneway, "reverse") || str_eq(oneway, "backward")) {
			return OSMWayDirectionCategory::only_open_backwards;
		} else if(str_eq(oneway, "yes") || str_eq(oneway, "true") || str_eq(oneway, "1")) {
			return OSMWayDirectionCategory::only_open_forwards;
		} else if(str_eq(oneway, "reversible") || str_eq(oneway, "alternating")) {
			return OSMWayDirectionCategory::closed;
		} else {
			log_message("Warning: OSM way "+std::to_string(osm_way_id)+" has unknown oneway tag value \""+oneway+"\" for \"oneway\". Way is closed.");
			return OSMWayDirectionCategory::closed;
		}
	}
}
```

**Comment by skinkie** [comment]
I think you have all your cases indeed :)

> What should happen with "oneway_bicycle=no_planned"

Ignore it, we are about the here and now. And if it becomes =no, it will be part of the graph.

**Comment by ben-strasser** [comment]
Hi,

I finally found some time to prepared wrap up some code. :) You can view it here https://github.com/ben-strasser/RoutingKit . 

I copied the following snippet from your code:
```cpp
	const char* crossing = tags["crossing"];
	if(crossing != nullptr && str_eq(crossing, "no"))
		return false;
```
Is that really desirable? The way I read the documentation in the wiki is that crossing a street at the point is not possible. However, this does not mean that one cannot drive along the way without crossing it. I think we should ignore the tag. 

Perhaps extending `get_osm_way_bicycle_comfort_level` could be useful.

I did not yet have the time to debug and test the code. If you have some free time then it would be very useful if you could compute a few routes and verify that the computed routes are reasonable.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
On woensdag 8 maart 2017 13:57:22 CET, ben-strasser wrote:
> I copied the following snippet from your code:
>
> 	const char* crossing = tags["crossing"];
> 	if(crossing != nullptr && str_eq(crossing, "no"))
> 		return false;
> Is that really desirable? The way I read the documentation in 
> the wiki is that crossing a street at the point is not possible. 
> However, this does not mean that one cannot drive along the way 
> without crossing it. I think we should ignore the tag.

I cannot be more clear than this:

"Where definitely no crossing is possible/legal. This tag must be used 
without a highway=crossing, so data consumers only evaluating the 
high-level highway tag are not mislead into assuming a crossing here. 
As crossing=no excludes the existence of a crossing, the combination of 
highway=crossing and crossing=no is invalid"

Tags without highway= are ignored anyway in the current graph processing.


> I did not yet have the time to debug and test the code. If you 
> have some free time then it would be very useful if you could 
> compute a few routes and verify that the computed routes are 
> reasonable.

Used this code extensively for making the Reddit map.

-- 
Stefan

**Comment by ben-strasser** [comment]
bicycle support in master

**Pull request closed without merging**
