### PR TITLE
Build on MSVC

### PR DESCRIPTION
**Pull request by Konijnendijk**
Added defines in bit_vector to make aligned memory allocation work. Added various workarounds for headers, types and builtins not available on MSVC.

Tested on Visual Studio 2015 (MSVC 14).

### CODE REVIEW

**Comment by ben-strasser** [comment]
Hi,

thanks for the patch. It is nice seeing someone compiling the code on MSVC. :)

I just committed variants of most of your changes to the master. There are two things left unresolved:

1. Why is `uint64_t v[8] = {0};` needed? For performance reasons they are intentionally left uninitialized. Does this break something?
2. The missing `BitVector::uninitialized` definition. Does changing 
```cpp
static const Uninitialized uninitialized;
```
to
```cpp
static constexpr Uninitialized uninitialized = {};
```
also solve the problem on MSVC without creating a definition in bit_vector.cpp? If this also solves the problem then I'd prefer this change.

Could you please review the other changes and verify that they do resolve the MSVC issues?

Best Regards
Ben Strasser

* ssize_t is signed. Defining it as unsigned can result in error values not being caught. That is thus not a good workaround. I fixed the problem by correcting the usage of fread to no longer use ssize_t.

**Comment by Konijnendijk** [comment]
I merged master into my branch and updated things according to your comments. The `aligned_free` define did not seem to be used, so I added another define and replace the call to `free` with `aligned_free`. 

1. The `uint64_t v[8] = {0};` is needed because in debug mode MSVC complains about uninitialized variables with a runtime error. 
2. Replacing this worked

**Comment by ben-strasser** [comment]
Hi,

fixed the remaining aligned_free issue, the ={0} issue, and added the constexpr. Everything is now in master. Could you please confirm that everything now works as expected with MSVC. Thanks for reporting the bug. :)

Best Regards
Ben Strasser

**Comment by Konijnendijk** [comment]
There's still a semicolon missing in `emulate_gcc_builtin.h` on line 22. The rest is working all right. 

Thanks for the quick responses!

**Comment by ben-strasser** [comment]
Semicolon added to master. :)

**Pull request closed without merging**
