### PR TITLE
Feature original arc

### PR DESCRIPTION
**Pull request by skinkie**
I was about to start a mail to @ben-strasser with the subject "Breaking my head on routingkit". When writing the email, my last resort in debugging, I stumbled upon the solution that I had been missing for the past days. In https://github.com/bliksemlabs/RoutingKit/blob/feature-original-arc/src/osm_graph_builder.cpp#L231 I assumed the arc indexes would remain in the initial order, which they didn't.

So this is my attempt to come up with a solution for issue #8. It is almost as naive as possible, but it does elegantly solve the reverse order case. Other then that: all routing nodes are duplicated in the arc. I am currently trying to use this duplication in my advantage as a short term solution for #19 case 1.

shape

### CODE REVIEW

**Comment by ben-strasser** [comment]
Hi,

I just ran a test on a Germany PBF. In the car graph there are 9514262 nodes but arc_path_latitude.size() is 55015441. This thus a comparatively large increase in memory consumption. However, not all applications need this information. I am therefore reluctant to implement it this way. Ideal would be some form of compression scheme that makes the memory overheat negligible. I do not know whether this is possible though.

I do not know what the best way to go forth from here.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
In my perspective; for a general implementation `get_node_path` is good enough. I guess we would first need to acquire some statistics on the average arc path length, to figure out if line simplification would assist in any way. For every arc the beginning and endpoint could be removed that would save at least 20% already, but requires another form of indexing. The code now implements 2-floats for modelling nodes, this could potentially be deltacoded, again need to know the outliers that would overflow a delta value. Another way would be in terms of using the polyline encoding, but both will kill other use cases such as #19 case 1.

**Comment by skinkie** [comment]
@ben-strasser with the last commit, featuring modelling nodes, we can close this one right?

**Comment by ben-strasser** [comment]
I'd still like to see a compression scheme. However, yes, this pull request can be closed.

**Pull request closed without merging**
